name: Main CI

on:
  pull_request:
    branches: ['tic-tac-toe']
  push:
    branches: ['tic-tac-toe']

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests
        run: npm run test:ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: 'tic-tac-toe'
